Adaptacion clientes a ubuntu

diff --git a/debian/controlies-ltspserver.postinst b/debian/controlies-ltspserver.postinst
--- a/debian/controlies-ltspserver.postinst
+++ b/debian/controlies-ltspserver.postinst
@@ -9,24 +9,35 @@ case "$1" in
     configure)
     #####################################################
     # Registro Post Session
-    DIR="gdm"
-    if [ -f "/etc/init.d/gdm3" ]; then
-        DIR="gdm3"
+    if [  -e /etc/lightdm ]
+    then #lightdm
+        #Cambiando ruta script cierre sesion
+        #session-cleanup-script=/usr/share/controlies-ltspserver/PostSession
+        sed -i 's/controlies-client/controlies-ltspserver/g'  /usr/share/controlies-ltspserver/14-logout.conf
+        #Copiandolo a lightdm.conf.d
+        cp -f /usr/share/controlies-ltspserver/14-logout.conf /etc/lightdm/lightdm.conf.d/14-logout.conf
+        chmod 644 /etc/lightdm/lightdm.conf.d/14-logout.conf
+
+    else #gdm o gdm3
+       DIR="gdm"
+       if [ -f "/etc/init.d/gdm3" ]; then
+           DIR="gdm3"
+       fi
+
+       if [ ! -f /etc/$DIR/PostSession/Default ]; then
+           echo "#!/bin/sh" >> /etc/$DIR/PostSession/Default
+       fi
+
+       sed -i.bak '/exit 0/d' /etc/$DIR/PostSession/Default
+
+       if ! grep "/usr/share/controlies-ltspserver/PostSession" /etc/$DIR/PostSession/Default
+       then
+          echo "/usr/share/controlies-ltspserver/PostSession" >> /etc/$DIR/PostSession/Default
+       fi
+
+       echo "exit 0" >> /etc/$DIR/PostSession/Default
+       chmod +x /etc/$DIR/PostSession/Default
     fi
-
-    if [ ! -f /etc/$DIR/PostSession/Default ]; then
-        echo "#!/bin/sh" >> /etc/$DIR/PostSession/Default
-    fi
-
-    sed -i.bak '/exit 0/d' /etc/$DIR/PostSession/Default
-
-    if ! grep "/usr/share/controlies-ltspserver/PostSession \$LOGNAME" /etc/$DIR/PostSession/Default
-    then
-      echo "/usr/share/controlies-ltspserver/PostSession \$LOGNAME" >> /etc/$DIR/PostSession/Default
-    fi
-
-    echo "exit 0" >> /etc/$DIR/PostSession/Default
-    chmod +x /etc/$DIR/PostSession/Default
     chmod 755 /usr/share/controlies-ltspserver/PostSession
     chmod 755 /usr/share/controlies-ltspserver/controlies-seguimiento
 
@@ -54,6 +65,9 @@ case "$1" in
     #chmod 644 /usr/share/pyshared/pkpgpdls/zjstream.py
     chmod 644 /etc/cups/tea4cups.conf
     chmod 700 /usr/lib/cups/backend/tea4cups
+    #Cambiando ruta script seguimiento impresión
+    sed -i 's/controlies-client/controlies-ltspserver/g' /etc/cups/tea4cups.conf
+ 
     service cups restart
 
     ######################################################
